version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: cloudfilmuser
      POSTGRES_PASSWORD: cloudfilmpassword
      POSTGRES_DB: cloudfilmdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db_data: